### ISSUE TITLE
RFC: Could We Integrate Data From The Parser With Arguflow Vault?

### ISSUE THREAD

**Issue by skeptrunedev** [densumesh/debatev-parsers#1]
Hello, the work that has been done on both the parser and front-end for this project is really amazing! We built a very similar tool that is a very extension of what you all have built here. We basically just added semantic search, the ability to create evidence, and the ability to rate evidence that is found via search. 

### Integration with [Arguflow Vault](https://vault.arguflow.com/)

In a lot more detail, I explain [what Vault is and our intentions for it in this blog post](https://blog.arguflow.com/posts/learn-about-what-arguflow-vault-is-and-our-planned-direction-for-it). But a TLDR is below. 

Arguflow vault is a website that allows users to create, query, and rate embeddings that consist of a link and arbitrary text content. 

Some of the key features are 

- semantic search 
- duplication prevention
- ability to upvote/downvote
- ability to view users' and cards' cumulative ratings 

### Contact Info 

If you all are interested by this and willing to help us migrate the data to our backend, that would be amazing! I figure that we will likely just end up using the parsers with some slight modifications. 

I should respond to any replies here on Github fairly quickly. Additionally, I would love to meet to talk about things more generally and have a [cal.com meeting link here](https://cal.com/nick-arguflow/1-hour-meeting?duration=60) .

**Comment by densumesh** [comment]
Hi Nick,

In order to integrate Debatev with ArguVault, what would we need to provide you with? Do you just want our help in parsing data or do you want access to our backend database?

**Comment by skeptrunedev** [comment]
Hey, we were actually able to figure it out. We bulk downloaded all of the briefs from opencaselist and are parsing all of the cards out of them actively now. Should be done in ~45 hours. 

The resulting data should be quite interesting. We are creating and storing embeddings for every card.

**Comment by skeptrunedev** [comment]
Brief aside, but when we are done, we plan to publish the full dataset as a csv for anyone who wants easy access. 

Not sure if we are going to be able to include the embeddings in that csv because I don't know how nicely Qdrant will play with Postgres across a join. However, we will definitely have all of the other fields.

**Comment by densumesh** [comment]
Ok, that sounds great! Whenever you do finish creating that csv, please link it here. I would be very interested in seeing that data.

**Comment by skeptrunedev** [comment]
We are also happy to send you the Qdrant volume if you want to stand up your own Qdrant instance. I'd like to do some clustering analysis on the embeddings when we are done. 

Overall, being able to throw the data into a pd dataframe will be amazing. There are probably lots of fun things to explore with it.

**Comment by densumesh** [comment]
Yes, that would be amazing! You already have my email, so if you could send the Qdrant volume my way once all the embeddings have been processed that would great.

**Comment by skeptrunedev** [comment]
Last thing, but we are also saving the html versions of all the cases such that we can put it behind a proxy and serve the static files. 

The "sign in to download" requirement is something I found a bit annoying.

**Comment by densumesh** [comment]
Yeah it is. When I scraped all of the docs, it was on the old version of the website which didn't require that. Personally, I just set the auth cookie in my scraping requests to get around it. 

I had another question though, what encoder are you using on the documents to get their embeddings?

**Comment by skeptrunedev** [comment]
Setting the auth cookie would be fine, but I didn't even want to bother. We can also provide a bit more value to users by just serving HTML versions of all the briefs. 

OpenAI's embeddings - https://platform.openai.com/docs/api-reference/embeddings 

We are self-funding Arguflow at this point, but I felt it worthwhile to just go with their embeddings. We are using the OpenAI Chat models for the AI Debate Coach at https://arguflow.com/ , so I figured I'd just keep it simple and use their embeddings too. The cost is fairly low. 

If you have time, it would be really great to meet with you. You can [book a time with this cal.com link](https://cal.com/nick-arguflow/1-hour-meeting?duration=60) . @fastfists and I have been developing in the dark, and it would be good to talk to some other folks if that at all interests you. I think it would be fun :) .

**Comment by densumesh** [comment]
Yeah I'd be down to talk with you guys. Would you be fine if I brought a colleague along with me?

**Comment by skeptrunedev** [comment]
Of course! The more the merrier!

**Comment by skeptrunedev** [comment]
Finally got all of the converted html versions up - https://oc.arguflow.com/
